export default {
  login: 'phantware',
  id: 32511206,
  node_id: 'MDQ6VXNlcjMyNTExMjA2',
  avatar_url: 'https://avatars.githubusercontent.com/u/32511206?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/phantware',
  html_url: 'https://github.com/phantware',
  followers_url: 'https://api.github.com/users/phantware/followers',
  following_url:
    'https://api.github.com/users/phantware/following{/other_user}',
  gists_url: 'https://api.github.com/users/phantware/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/phantware/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/phantware/subscriptions',
  organizations_url: 'https://api.github.com/users/phantware/orgs',
  repos_url: 'https://api.github.com/users/phantware/repos',
  events_url: 'https://api.github.com/users/phantware/events{/privacy}',
  received_events_url: 'https://api.github.com/users/phantware/received_events',
  type: 'User',
  site_admin: false,
  name: 'Ismail Jamiu Babatunde',
  company: 'phantmoney2011@gmail.com',
  blog: '',
  location: 'Lagos, Nigeria',
  email: null,
  hireable: true,
  bio: 'Experienced Dynamic 365/NAV functional expert, Back-end Developer with a demonstrated history of working in the information technology and services industry. ',
  twitter_username: 'IsmailJamiuBab1',
  public_repos: 74,
  public_gists: 4,
  followers: 5,
  following: 30,
  created_at: '2017-10-04T10:02:10Z',
  updated_at: '2022-01-06T14:37:54Z',
}
